name: CD EC2 (DEV + PRD)

on:
  workflow_run:
    workflows: ["Go CI + Sonar + DockerHub"]
    types: [completed]

jobs:
  debug:
      runs-on: ubuntu-latest
      steps:
        - run: echo "CD disparou! branch=${{ github.event.workflow_run.head_branch }} status=${{ github.event.workflow_run.conclusion }}"
  deploy-dev:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy DEV
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY_DEV }}
          script: |
            cd ~/pet-ms
            git pull origin dev
            docker compose -f docker-compose.dev.yml pull
            docker compose -f docker-compose.dev.yml up -d

  deploy-prd:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy PRD
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST_PRD }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY_PRD }}
          script: |
            cd ~/pet-ms
            git pull origin main
            docker compose -f docker-compose.prd.yml pull
            docker compose -f docker-compose.prd.yml up -d
