# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "dev", "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test-sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Deps
        run: go mod download

      - name: Tests
        run: go test -v ./...

      - name: Coverage
        run: go test $(go list ./... | grep -v '/proto' | grep -v '/domain/repository' | grep -v '/init') -coverprofile=coverage.out

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=LuizFJP_pet-ms
            -Dsonar.organization=luizfjp
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=coverage.out

  docker:
    runs-on: ubuntu-latest
    needs: test-sonar
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: luizportel4/pet-ms
          tags: |
            type=raw,value=dev,enable=${{ startsWith(github.ref, 'refs/heads/dev') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/main') }}
            type=sha,enable=true,priority=50
            
            type=raw,value=1.0.${{ github.run_number }},enable=${{ startsWith(github.ref, 'refs/heads/main') }}

            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
