# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI + Sonar + DockerHub

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test-sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Deps
        run: go mod download

      - name: Tests
        run: go test -v ./...

      - name: Coverage
        run: go test ./... -coverprofile=coverage.out

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=LuizFJP_pet-ms
            -Dsonar.organization=luizfjp
            -Dsonar.sources=.
            -Dsonar.go.coverage.reportPaths=coverage.out

      - name: Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        timeout-minutes: 5

  docker:
    runs-on: ubuntu-latest
    needs: test-sonar
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: LuizFJP/pet-ms   # troque pro repo do micro atual
          tags: |
            type=raw,value=dev,enable={{ startsWith(github.ref, 'refs/heads/dev') }}
            type=raw,value=latest,enable={{ startsWith(github.ref, 'refs/heads/main') }}
            type=sha,enable=true,priority=50

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
